export const CAR_BRANDS = [
  'Acura', 'Alfa Romeo', 'Audi', 'BMW', 'BYD', 'Cadillac', 'Changan',
  'Chery', 'Chevrolet', 'Citroen', 'Daewoo', 'Datsun', 'Dodge', 'Fiat',
  'Ford', 'Geely', 'Genesis', 'Great Wall', 'Haval', 'Honda', 'Hyundai',
  'Infiniti', 'JAC', 'Jeep', 'Kia', 'Lada', 'Land Rover', 'Lexus',
  'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan', 'Opel',
  'Peugeot', 'Porsche', 'Renault', 'Skoda', 'SsangYong', 'Subaru',
  'Suzuki', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo', 'UAZ', 'ГАЗ',
  'ВАЗ', 'ЗАЗ', 'Москвич'
]

export const CAR_MODELS: Record<string, string[]> = {
  'Toyota': ['Camry', 'Corolla', 'RAV4', 'Highlander', 'Land Cruiser', 'Supra', 'Yaris', 'Hilux'],
  'BMW': ['3 серия', '5 серия', '7 серия', 'X3', 'X5', 'X7', 'M3', 'M5'],
  'Mercedes-Benz': ['C-Класс', 'E-Класс', 'S-Класс', 'GLC', 'GLE', 'AMG GT'],
  'Audi': ['A3', 'A4', 'A6', 'A8', 'Q5', 'Q7', 'Q8', 'RS6'],
  'Kia': ['Rio', 'Sportage', 'Sorento', 'Ceed', 'K5', 'Stinger', 'Carnival'],
  'Hyundai': ['Solaris', 'Tucson', 'Santa Fe', 'Creta', 'Sonata', 'Accent', 'Palisade'],
  'Volkswagen': ['Polo', 'Golf', 'Passat', 'Tiguan', 'Touareg', 'Arteon'],
  'Nissan': ['Qashqai', 'X-Trail', 'Altima', 'Sentra', 'Patrol', 'Juke'],
  'Mazda': ['3', '6', 'CX-5', 'CX-9', 'MX-5'],
  'Lada': ['Vesta', 'Granta', 'Largus', 'Niva', 'XRAY', 'Vesta Cross'],
  'Renault': ['Duster', 'Kaptur', 'Logan', 'Sandero', 'Megane', 'Koleos'],
  'Skoda': ['Octavia', 'Superb', 'Karoq', 'Kodiaq', 'Rapid', 'Fabia'],
  'Ford': ['Focus', 'Mondeo', 'Explorer', 'Escape', 'Mustang', 'F-150'],
  'Chevrolet': ['Cruze', 'Malibu', 'Tahoe', 'Camaro', 'Spark', 'Trailblazer'],
  'Honda': ['Civic', 'Accord', 'CR-V', 'HR-V', 'Pilot'],
  'Subaru': ['Forester', 'Outback', 'XV', 'Impreza', 'WRX'],
  'Suzuki': ['Swift', 'Vitara', 'Jimny', 'SX4', 'Across'],
  'Mitsubishi': ['Outlander', 'ASX', 'L200', 'Pajero', 'Eclipse Cross'],
  'Geely': ['Coolray', 'Atlas', 'Emgrand', 'Tugella', 'Azkarra'],
  'Haval': ['F7', 'F7x', 'Jolion', 'H6', 'Dargo'],
  'Chery': ['Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Tiggo 4', 'Omoda 5'],
  'BYD': ['Han', 'Tang', 'Song Plus', 'Qin Plus', 'Seal', 'Atto 3'],
  'Lexus': ['RX', 'NX', 'ES', 'LS', 'IS', 'GX'],
  'Porsche': ['Cayenne', 'Macan', 'Panamera', '911', 'Taycan'],
  'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X'],
  'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  'Volvo': ['XC60', 'XC90', 'S60', 'S90', 'V60', 'XC40'],
  'Jeep': ['Grand Cherokee', 'Wrangler', 'Compass', 'Cherokee', 'Gladiator'],
  'Dodge': ['Challenger', 'Charger', 'Durango', 'Ram'],
  'UAZ': ['Patriot', 'Hunter', 'Патриот', 'Буханка'],
  'ГАЗ': ['ГАЗель', 'Соболь', 'Волга'],
  'ЗАЗ': ['Forza', 'Sens', 'Lanos'],
  'Москвич': ['3', '6', '8']
}
